name: build

on:
  workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: |
           echo "::group::Foo"
           echo "Foo1"
           echo "Foo2"
           echo "Foo3"
           echo "Foo4"
           echo "::endgroup"
           echo "::group::Foo2"
           echo "FooA"
           echo "FooB"
           echo "FooC"
           echo "FooD"
           echo "::endgroup"
           echo "::add-mask::Mona The Octocat"
           echo Here too we can see the same build configuration: $TEST

      
  
